web:
   image: ubuntu/apache2:php 
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "8080:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "3306:3306"
